name: Word Count in Markdown Files

on:
  push:
    branches:
      - '**'

jobs:
  word_count:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Count words in Markdown files
        run: |
          total_words=0
          for file in $(find . -name "*.md"); do
            words=$(wc -w < "$file")
            echo "$file: $words words"
            total_words=$((total_words + words))
          done
          echo "Total: $total_words words"